import torch

from model import BDHModel


# ============================================================
# CONFIG
# ============================================================

MODEL_PATH = "bdh_model.pt"

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

MAX_NEW_BYTES = 300

TEMPERATURE = 0.8

TOP_K = 20


# ============================================================
# LOAD CHECKPOINT
# ============================================================

checkpoint = torch.load(
    MODEL_PATH,
    map_location=DEVICE
)

N = checkpoint["n"]
D = checkpoint["d"]
NUM_LAYERS = checkpoint["num_layers"]

print("Loading model...")
print(f"N: {N}")
print(f"D: {D}")
print(f"Layers: {NUM_LAYERS}")
print(f"Device: {DEVICE}")


# ============================================================
# CREATE MODEL
# ============================================================

model = BDHModel(
    num_layers=NUM_LAYERS,
    n=N,
    d=D
).to(DEVICE)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

model.eval()

print("Model loaded.\n")


# ============================================================
# TEXT -> BYTES
# ============================================================

def text_to_tensor(text):
    data = list(text.encode("utf-8"))

    return torch.tensor(
        data,
        dtype=torch.long,
        device=DEVICE
    ).unsqueeze(0)


# ============================================================
# TOP-K SAMPLING
# ============================================================

def sample_next_byte(logits):

    logits = logits / TEMPERATURE

    values, indices = torch.topk(
        logits,
        min(TOP_K, logits.size(-1))
    )

    probabilities = torch.softmax(
        values,
        dim=-1
    )

    sampled = torch.multinomial(
        probabilities,
        num_samples=1
    )

    next_byte = indices.gather(
        -1,
        sampled
    )

    return next_byte


# ============================================================
# GENERATE
# ============================================================

@torch.no_grad()
def generate(prompt, max_new_bytes=MAX_NEW_BYTES):

    # --------------------------------------------------------
    # Encode prompt
    # --------------------------------------------------------

    input_ids = text_to_tensor(prompt)

    # --------------------------------------------------------
    # Feed prompt through model
    #
    # This builds the recurrent BDH state.
    # --------------------------------------------------------

    logits, rhos = model(
        input_ids,
        None
    )

    generated = list(
        prompt.encode("utf-8")
    )

    # --------------------------------------------------------
    # Generate one byte at a time
    # --------------------------------------------------------

    for _ in range(max_new_bytes):

        last_logits = logits[:, -1, :]

        next_byte = sample_next_byte(
            last_logits
        )

        byte_value = next_byte.item()

        generated.append(byte_value)

        # ----------------------------------------------------
        # Feed generated byte back into BDH
        # ----------------------------------------------------

        next_input = next_byte

        logits, rhos = model(
            next_input,
            rhos
        )

    # --------------------------------------------------------
    # Decode bytes
    # --------------------------------------------------------

    result = bytes(generated)

    try:
        return result.decode("utf-8")
    except UnicodeDecodeError:
        return result.decode(
            "utf-8",
            errors="replace"
        )


# ============================================================
# INTERACTIVE LOOP
# ============================================================

while True:

    prompt = input("Prompt (type 'exit' to quit): ")

    if prompt.lower() == "exit":
        break

    print("\n--- Generated ---")

    output = generate(
        prompt,
        MAX_NEW_BYTES
    )

    print(output)

    print("-----------------\n")